version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_exchange
    ports:
      - "6379:6379"
      
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: timescaledb_exchange
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: exchange_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - timescale-data:/var/lib/postgresql/data

volumes:
  timescale-data: